theme: jekyll-theme-leap-day

twitter_username: fronteirases # DO NOT include the @ character, or else the build will fail!
github_username:  fronteirases # DO NOT include the @ character, or else the build will fail!
instagram_username: fronteirases

relative_links:
  enabled: true
  collections: true
include:
  - index.md

serve_og_meta: true # Include Open Graph meta tags in the HTML head
og_image: logo.png # The site-wide (default for all links) Open Graph preview image

