theme: minimal  # era jekyll-theme-leap-day

#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#logo: /logo.png

twitter_username: fronteirases # DO NOT include the @ character, or else the build will fail!
github_username:  fronteirases # DO NOT include the @ character, or else the build will fail!
instagram_username: fronteirases

relative_links:
  enabled: true
  collections: true
include:
  - index.md


